apiVersion: v1
kind: Service
metadata:
  name: api-service 
  namespace: app-go 
  labels:
    app: api-go-service
spec:
  selector:
    api: api-go 
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: api
    port: 80
    targetPort: 8080
